// Generated by scripts/export_mcp_contract.py. Do not edit.
export const SMART_SCHEMAS = {
  "engraphis_conflict_review": {
    "properties": {
      "limit": {
        "default": 50,
        "description": "Max items to return.",
        "maximum": 100,
        "minimum": 1,
        "title": "Limit",
        "type": "integer"
      },
      "repo": {
        "anyOf": [
          {
            "maxLength": 200,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional repository scope.",
        "title": "Repo"
      },
      "workspace": {
        "default": "default",
        "description": "Workspace to review.",
        "maxLength": 200,
        "title": "Workspace",
        "type": "string"
      }
    },
    "title": "engraphis_conflict_reviewArguments",
    "type": "object"
  },
  "engraphis_discover_actions": {
    "properties": {
      "category": {
        "default": "",
        "description": "Optional area: memory, governance, code, audit, or ops.",
        "maxLength": 100,
        "title": "Category",
        "type": "string"
      },
      "intent": {
        "default": "any",
        "description": "Optional side effect: any, read, write, admin, or destructive.",
        "pattern": "^(any|read|write|admin|destructive)$",
        "title": "Intent",
        "type": "string"
      },
      "limit": {
        "default": 1,
        "description": "Number of ranked actions to return.",
        "maximum": 3,
        "minimum": 1,
        "title": "Limit",
        "type": "integer"
      },
      "task": {
        "description": "Describe the capability needed, without pasting memory content.",
        "maxLength": 2000,
        "minLength": 1,
        "title": "Task",
        "type": "string"
      }
    },
    "required": [
      "task"
    ],
    "title": "engraphis_discover_actionsArguments",
    "type": "object"
  },
  "engraphis_execute_action": {
    "properties": {
      "arguments": {
        "additionalProperties": true,
        "description": "Arguments matching the discovered schema.",
        "title": "Arguments",
        "type": "object"
      },
      "capability_id": {
        "description": "Capability id returned by discover_actions.",
        "maxLength": 128,
        "minLength": 8,
        "title": "Capability Id",
        "type": "string"
      },
      "schema_digest": {
        "description": "Schema digest returned by discovery.",
        "maxLength": 128,
        "minLength": 8,
        "title": "Schema Digest",
        "type": "string"
      }
    },
    "required": [
      "capability_id",
      "schema_digest",
      "arguments"
    ],
    "title": "engraphis_execute_actionArguments",
    "type": "object"
  },
  "engraphis_execute_read": {
    "properties": {
      "arguments": {
        "additionalProperties": true,
        "description": "Arguments matching the discovered schema.",
        "title": "Arguments",
        "type": "object"
      },
      "capability_id": {
        "description": "Capability id returned by discover_actions.",
        "maxLength": 128,
        "minLength": 8,
        "title": "Capability Id",
        "type": "string"
      },
      "schema_digest": {
        "description": "Schema digest returned by discovery.",
        "maxLength": 128,
        "minLength": 8,
        "title": "Schema Digest",
        "type": "string"
      }
    },
    "required": [
      "capability_id",
      "schema_digest",
      "arguments"
    ],
    "title": "engraphis_execute_readArguments",
    "type": "object"
  },
  "engraphis_get_memory": {
    "properties": {
      "memory_id": {
        "description": "Memory id to read.",
        "maxLength": 200,
        "minLength": 1,
        "title": "Memory Id",
        "type": "string"
      },
      "repo": {
        "anyOf": [
          {
            "maxLength": 200,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional repository scope.",
        "title": "Repo"
      },
      "workspace": {
        "default": "default",
        "description": "Workspace containing the memory.",
        "maxLength": 200,
        "title": "Workspace",
        "type": "string"
      }
    },
    "required": [
      "memory_id"
    ],
    "title": "engraphis_get_memoryArguments",
    "type": "object"
  },
  "engraphis_recall_context": {
    "properties": {
      "format": {
        "default": "full",
        "description": "Context format: 'full' or 'gist'.",
        "title": "Format",
        "type": "string"
      },
      "k": {
        "default": 50,
        "description": "Maximum source memories.",
        "maximum": 50,
        "minimum": 1,
        "title": "K",
        "type": "integer"
      },
      "query": {
        "description": "Question or task needing prior context.",
        "maxLength": 100000,
        "minLength": 1,
        "title": "Query",
        "type": "string"
      },
      "repo": {
        "anyOf": [
          {
            "maxLength": 200,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional repository.",
        "title": "Repo"
      },
      "session_id": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional active session.",
        "title": "Session Id"
      },
      "token_budget": {
        "default": 1024,
        "description": "Hard returned-context token budget.",
        "maximum": 32768,
        "minimum": 0,
        "title": "Token Budget",
        "type": "integer"
      },
      "workspace": {
        "anyOf": [
          {
            "maxLength": 200,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional workspace.",
        "title": "Workspace"
      }
    },
    "required": [
      "query"
    ],
    "title": "smart_recall_contextArguments",
    "type": "object"
  },
  "engraphis_remember": {
    "properties": {
      "claim_kind": {
        "default": "",
        "description": "Optional claim predicate/category (for example 'configured_value').",
        "maxLength": 200,
        "title": "Claim Kind",
        "type": "string"
      },
      "content": {
        "description": "Durable fact, decision, preference, or procedure.",
        "maxLength": 100000,
        "minLength": 1,
        "title": "Content",
        "type": "string"
      },
      "importance": {
        "default": 0.0,
        "description": "Salience from 0 to 1.",
        "maximum": 1.0,
        "minimum": 0.0,
        "title": "Importance",
        "type": "number"
      },
      "mtype": {
        "default": "semantic",
        "description": "semantic, episodic, procedural, or working.",
        "title": "Mtype",
        "type": "string"
      },
      "repo": {
        "anyOf": [
          {
            "maxLength": 200,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional repository.",
        "title": "Repo"
      },
      "session_id": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional active session.",
        "title": "Session Id"
      },
      "subject_key": {
        "default": "",
        "description": "Optional stable claim subject (for example 'api.rate_limit'). Matching keys make supersession safer and deterministic.",
        "maxLength": 1000,
        "title": "Subject Key",
        "type": "string"
      },
      "workspace": {
        "default": "default",
        "description": "Workspace for the memory.",
        "maxLength": 200,
        "title": "Workspace",
        "type": "string"
      }
    },
    "required": [
      "content"
    ],
    "title": "smart_rememberArguments",
    "type": "object"
  },
  "engraphis_session": {
    "properties": {
      "action": {
        "default": "start",
        "description": "start to resume work, or end to save its handoff.",
        "title": "Action",
        "type": "string"
      },
      "agent": {
        "default": "",
        "description": "Optional agent name.",
        "maxLength": 200,
        "title": "Agent",
        "type": "string"
      },
      "force_new": {
        "default": false,
        "description": "Start only: branch a new session instead of reusing an exact active task.",
        "title": "Force New",
        "type": "boolean"
      },
      "goal": {
        "default": "",
        "description": "Task goal; start returns bounded relevant context.",
        "maxLength": 1000,
        "title": "Goal",
        "type": "string"
      },
      "open_threads": {
        "anyOf": [
          {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Unresolved follow-ups.",
        "title": "Open Threads"
      },
      "outcome": {
        "default": "",
        "description": "Optional outcome label.",
        "maxLength": 1000,
        "title": "Outcome",
        "type": "string"
      },
      "repo": {
        "anyOf": [
          {
            "maxLength": 200,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional repository scope.",
        "title": "Repo"
      },
      "session_id": {
        "default": "",
        "description": "Session id required to end a session.",
        "maxLength": 200,
        "title": "Session Id",
        "type": "string"
      },
      "summary": {
        "default": "",
        "description": "Short final handoff.",
        "maxLength": 100000,
        "title": "Summary",
        "type": "string"
      },
      "token_budget": {
        "default": 512,
        "description": "Goal-context budget when starting.",
        "maximum": 32768,
        "minimum": 0,
        "title": "Token Budget",
        "type": "integer"
      },
      "workspace": {
        "default": "default",
        "description": "Workspace for a started session.",
        "maxLength": 200,
        "title": "Workspace",
        "type": "string"
      }
    },
    "title": "engraphis_sessionArguments",
    "type": "object"
  },
  "engraphis_update_memory": {
    "properties": {
      "actor": {
        "default": "user",
        "description": "Optional local-mode actor label; authenticated team mode uses the caller identity.",
        "maxLength": 200,
        "title": "Actor",
        "type": "string"
      },
      "importance": {
        "anyOf": [
          {
            "maximum": 1.0,
            "minimum": 0.0,
            "type": "number"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional importance 0..1.",
        "title": "Importance"
      },
      "memory_id": {
        "description": "Memory id to update.",
        "maxLength": 200,
        "minLength": 1,
        "title": "Memory Id",
        "type": "string"
      },
      "mtype": {
        "anyOf": [
          {
            "maxLength": 50,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional memory type (working|episodic|semantic|procedural).",
        "title": "Mtype"
      },
      "repo": {
        "anyOf": [
          {
            "maxLength": 200,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional repository scope.",
        "title": "Repo"
      },
      "title": {
        "anyOf": [
          {
            "maxLength": 500,
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "description": "Optional new title.",
        "title": "Title"
      },
      "workspace": {
        "default": "default",
        "description": "Workspace containing the memory.",
        "maxLength": 200,
        "title": "Workspace",
        "type": "string"
      }
    },
    "required": [
      "memory_id"
    ],
    "title": "engraphis_update_memoryArguments",
    "type": "object"
  }
} as const;
