"""engraphis-init — one command from `pip install` to a configured, agent-connected setup.

Closes the biggest first-run gap: without configuration the
DB path defaults to the *package* directory, which is site-packages on a pip install.
This writes a project-local `.env` (absolute `ENGRAPHIS_DB_PATH`, optional API token),
then prints the exact MCP snippets to paste into Claude Code / Cursor / Cline / Zed.

    engraphis-init                 # write ./.env (kept if it exists), print next steps
    engraphis-init --db ~/mem.db   # choose the database location
    engraphis-init --token         # also generate a bearer token for the HTTP APIs
    engraphis-init --force         # overwrite an existing .env
    engraphis-init --check         # doctor: verify install, extras, DB writability

Non-interactive by design (no prompts): safe in scripts, CI, and agent shells.
"""
from __future__ import annotations

import argparse
import json
import secrets
import sqlite3
import sys
import time
from pathlib import Path


def _ok(label: str, detail: str = "") -> None:
    print(f"  [ok]      {label}" + (f" — {detail}" if detail else ""))


def _miss(label: str, detail: str = "") -> None:
    print(f"  [--]      {label}" + (f" — {detail}" if detail else ""))


def _fail(label: str, detail: str = "") -> None:
    print(f"  [FAIL]    {label}" + (f" — {detail}" if detail else ""))


def _try_import(name: str):
    try:
        return __import__(name)
    except Exception:
        return None


def cmd_check() -> int:
    """Doctor: report what's installed and whether the configured DB is usable."""
    failures = 0
    print(f"engraphis doctor — python {sys.version.split()[0]}")

    if _try_import("numpy") is None:
        _fail("numpy (required core)", "pip install numpy")
        failures += 1
    else:
        _ok("numpy (required core)")

    for mod, label, hint in [
        ("mcp", "MCP server extra", 'pip install "engraphis[mcp]"'),
        ("fastapi", "REST/Inspector extra", 'pip install "engraphis[server]"'),
        ("sentence_transformers", "real embeddings",
         "optional — deterministic offline embedder is the fallback"),
        ("tree_sitter", "AST code indexing",
         "optional — regex code indexer is the fallback"),
    ]:
        (_ok if _try_import(mod) else _miss)(label, hint if not _try_import(mod) else "")

    from engraphis.config import settings
    db = Path(settings.db_path).expanduser()
    try:
        db.parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(str(db))
        conn.execute("PRAGMA user_version")
        conn.close()
        _ok("database writable", str(db))
    except Exception as exc:
        _fail("database writable", f"{db}: {exc}")
        failures += 1

    try:
        from engraphis import licensing
        lic = licensing.current_license(refresh=True)
        err = licensing.license_error()
        if err:
            _miss("license", f"key rejected: {err}")
        elif not lic.is_paid:
            _ok("license", "free tier — all core features available")
        else:
            expiry = ("expires " + time.strftime("%Y-%m-%d", time.gmtime(lic.expires))
                      if lic.expires else "perpetual")
            _ok("license", f"{lic.plan} tier "
                           f"({', '.join(sorted(lic.features))}) — {expiry}")
    except Exception as exc:  # never let licensing break the doctor
        _miss("license", str(exc))

    print("all good ✓" if failures == 0 else f"{failures} problem(s) found")
    return 0 if failures == 0 else 1


def _env_content(db_path: Path, token: str) -> str:
    lines = [
        "# Engraphis — generated by engraphis-init. Full reference: .env.example",
        f"ENGRAPHIS_DB_PATH={db_path}",
    ]
    if token:
        lines += [
            "# Bearer token required by the REST server & Inspector APIs:",
            f"ENGRAPHIS_API_TOKEN={token}",
        ]
    lines += [
        "# Unlock Pro/Team (analytics, export, multi-user). A key can live here OR in",
        "# ~/.engraphis/license.key (the Inspector's license dialog writes that file).",
        "# ENGRAPHIS_LICENSE_KEY=ENGR1.xxxxx.yyyyy",
        "# ENGRAPHIS_TEAM_MODE=1",
    ]
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="engraphis-init", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--db", default="engraphis.db",
                    help="database file (default: ./engraphis.db)")
    ap.add_argument("--token", action="store_true",
                    help="generate an ENGRAPHIS_API_TOKEN for the HTTP APIs")
    ap.add_argument("--force", action="store_true", help="overwrite an existing .env")
    ap.add_argument("--check", action="store_true",
                    help="doctor mode: verify the installation instead of writing .env")
    args = ap.parse_args(argv)

    if args.check:
        return cmd_check()

    db_path = Path(args.db).expanduser().resolve()
    env_file = Path.cwd() / ".env"
    token = secrets.token_urlsafe(24) if args.token else ""

    if env_file.exists() and not args.force:
        print(f".env already exists at {env_file} — kept (use --force to overwrite).")
    else:
        env_file.write_text(_env_content(db_path, token), encoding="utf-8")
        print(f"wrote {env_file}")
        print(f"  database → {db_path}")
        if token:
            print("  api token → generated (in .env; send as 'Authorization: Bearer …')")

    snippet = {"mcpServers": {"engraphis": {
        "command": "engraphis-mcp",
        "env": {"ENGRAPHIS_DB_PATH": str(db_path)},
    }}}
    print("\nConnect your agent — Claude Code:")
    print(f'  claude mcp add engraphis --env ENGRAPHIS_DB_PATH="{db_path}"'
          " -- engraphis-mcp")
    print("\nCursor / Cline / Zed / Windsurf (mcp config):")
    print(json.dumps(snippet, indent=2))
    print("\nNext steps:")
    print("  engraphis-inspector      # product UI on http://127.0.0.1:8710")
    print("  engraphis-init --check   # verify the install")
    print("  Free forever at the core — Pro/Team unlock: "
          "https://github.com/Coding-Dev-Tools/engraphis#free-forever-vs-pro")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
